### Numpy -> Packages for Multidimensional array

In [2]:
import numpy as np

In [2]:
simple_list=[6,7,8]
np.array(simple_list)

array([6, 7, 8])

In [4]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [6]:
listoflists=[[1,2,4],[3,4,6],[5,6,8]]
np.array(listoflists)

array([[1, 2, 4],
       [3, 4, 6],
       [5, 6, 8]])

In [7]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [8]:
np.arange(5,100)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
       73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
       90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
np.arange(1,31,5) #shift+tab->help box

array([ 1,  6, 11, 16, 21, 26])

In [10]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros(4,int)

array([0, 0, 0, 0])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.zeros((2,3),int)

array([[0, 0, 0],
       [0, 0, 0]])

In [16]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [18]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [35]:
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
np.random.rand(1,4)

array([[0.10908986, 0.04204748, 0.20817529, 0.89241582]])

In [33]:
arr=np.random.randn(2,4)
arr

array([[-1.49216077,  0.81163652, -1.13222685,  0.61562427],
       [-0.18471667, -1.81947867, -0.78545328, -0.01815457]])

In [36]:
np.random.randint(1,100)

37

In [38]:
np.random.randint(1,11,100)

array([ 7,  2,  8, 10,  7,  7,  7,  8,  8,  7,  5, 10,  4,  3,  2,  8,  7,
       10,  1,  4,  8,  3, 10,  9,  5,  7,  6,  3,  7,  5,  1,  7,  1,  9,
        8,  4, 10,  3,  7,  3,  7, 10,  2,  1,  9,  1, 10,  4,  9,  7,  4,
        9,  3,  5,  9,  4,  9,  7,  5,  6,  4,  4,  1,  5,  7,  3,  1,  6,
        3,  2,  6,  4,  7,  7,  1,  9,  5,  4,  1, 10,  1,  5,  2,  4,  1,
        8,  3,  6,  9,  9,  3,  8, 10,  2,  8,  6, 10,  3,  7, 10])

In [6]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [8]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [9]:
sample_array.max()

29

In [11]:
sample_array.argmax() #index of max value

29

In [12]:
n=np.eye(5)
n

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
n.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
n=np.random.rand(2,3)
n

array([[0.11192572, 0.90123462, 0.01630135],
       [0.65935911, 0.28400886, 0.77371641]])

In [16]:
n.T

array([[0.11192572, 0.65935911],
       [0.90123462, 0.28400886],
       [0.01630135, 0.77371641]])

In [17]:
sample_array=np.arange(10,20)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
sample_array[0]

10

In [19]:
sample_array[2:5]

array([12, 13, 14])

In [20]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19])

In [22]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [23]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [24]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [25]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

## Two Dimensional Array

In [26]:
import numpy as np

In [27]:
sample_matrix=np.array([[1,23,33],[12,3,40],[2,55,67]])
sample_matrix

array([[ 1, 23, 33],
       [12,  3, 40],
       [ 2, 55, 67]])

In [29]:
sample_matrix[1,2]

40

In [30]:
sample_matrix[2,:]

array([ 2, 55, 67])

In [34]:
sample_matrix[:,(0,2)]

array([[ 1, 33],
       [12, 40],
       [ 2, 67]])

In [33]:
sample_matrix[2]

array([ 2, 55, 67])