## Selection Techniques

In [1]:
import numpy as np

In [4]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [5]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [6]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [7]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [8]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [9]:
np.max(sample_array)

19

In [10]:
np.min(sample_array)

1

In [11]:
np.argmax(sample_array)

18

In [12]:
np.argmin(sample_array)

0

In [13]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [14]:
np.std(sample_array)

5.477225575051661

In [15]:
np.var(sample_array)

30.0

In [16]:
np.mean(sample_array)

10.0

In [19]:
array=np.random.randn(3,4)
array

array([[ 1.08518012,  0.64929039, -0.96167965,  1.51733402],
       [ 0.30836543,  0.73431211,  1.28857353, -1.34523223],
       [-0.5589375 , -0.40201737,  1.03778985, -2.89485564]])

In [22]:
np.round(array,decimals=2)

array([[ 1.09,  0.65, -0.96,  1.52],
       [ 0.31,  0.73,  1.29, -1.35],
       [-0.56, -0.4 ,  1.04, -2.89]])

In [24]:
sport=np.array(['golf','apple','golf','fball'])
np.unique(sport)

array(['apple', 'fball', 'golf'], dtype='<U5')

## Pandas

In [25]:
import pandas as pd
import numpy as np

In [26]:
labels=['w','y','x','z']
sample_list=[100,200,300,400]
array=np.array([1,2,3,4])
dict={'w':10,'y':20,'x':30,'z':40}

In [27]:
pd.Series(data=sample_list) #series for single-D data

0    100
1    200
2    300
3    400
dtype: int64

In [28]:
pd.Series(data=sample_list,index=array)

1    100
2    200
3    300
4    400
dtype: int64

In [29]:
pd.Series(array,labels)

w    1
y    2
x    3
z    4
dtype: int32

In [30]:
pd.Series(dict)

w    10
y    20
x    30
z    40
dtype: int64

### Pandas dataframe and indexing

In [32]:
sports1=pd.Series([1,2,3,4],index=['cricket','golf','fball','baseball'])
sports1

cricket     1
golf        2
fball       3
baseball    4
dtype: int64

In [33]:
sports1['fball']

3

In [38]:
sports2=pd.Series([11,2,3,4],index=['cricket','golf','fball','basketball'])
sports2

cricket       11
golf           2
fball          3
basketball     4
dtype: int64

In [39]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
fball          6.0
golf           4.0
dtype: float64

In [37]:
import pandas as pd
import numpy as np

In [45]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(), columns= 'score1 score2 score3 score4 score5'.split())
df1

score1    score2    score3    score4    score5
A  0.649427  0.242063  0.471407  0.470853  0.773494
B  0.919001  0.955318  0.912695  0.999313  0.348957
C  0.473215  0.683438  0.054887  0.087914  0.952287
D  0.433743  0.140649  0.496014  0.157476  0.787025
E  0.125890  0.794893  0.198277  0.737852  0.067723
F  0.600216  0.259651  0.342967  0.358722  0.354715
G  0.629014  0.605929  0.342560  0.489127  0.763358
H  0.286947  0.726968  0.848276  0.716609  0.044366

In [46]:
df1["score1"]

A    0.649427
B    0.919001
C    0.473215
D    0.433743
E    0.125890
F    0.600216
G    0.629014
H    0.286947
Name: score1, dtype: float64

In [47]:
df1[["score1","score2","score3"]]

score1    score2    score3
A  0.649427  0.242063  0.471407
B  0.919001  0.955318  0.912695
C  0.473215  0.683438  0.054887
D  0.433743  0.140649  0.496014
E  0.125890  0.794893  0.198277
F  0.600216  0.259651  0.342967
G  0.629014  0.605929  0.342560
H  0.286947  0.726968  0.848276

In [49]:
df1['score6']=df1['score1']+df1['score3']
df1

score1    score2    score3    score4    score5    score6
A  0.649427  0.242063  0.471407  0.470853  0.773494  1.120833
B  0.919001  0.955318  0.912695  0.999313  0.348957  1.831697
C  0.473215  0.683438  0.054887  0.087914  0.952287  0.528102
D  0.433743  0.140649  0.496014  0.157476  0.787025  0.929757
E  0.125890  0.794893  0.198277  0.737852  0.067723  0.324167
F  0.600216  0.259651  0.342967  0.358722  0.354715  0.943183
G  0.629014  0.605929  0.342560  0.489127  0.763358  0.971573
H  0.286947  0.726968  0.848276  0.716609  0.044366  1.135223

In [54]:
df2={'ID':[122,123,124,125],'NAME':['John','Mark','Mary','Sam'],'Profit':[100,110,121,122]}
df=pd.DataFrame(df2)
df

ID  NAME  Profit
0  122  John     100
1  123  Mark     110
2  124  Mary     121
3  125   Sam     122

In [58]:
df["ID"]

0    122
1    123
2    124
3    125
Name: ID, dtype: int64

In [56]:
df[['ID','NAME','Profit']]

ID  NAME  Profit
0  122  John     100
1  123  Mark     110
2  124  Mary     121
3  125   Sam     122

In [59]:
df=df.drop('ID',axis=1)

In [60]:
df

NAME  Profit
0  John     100
1  Mark     110
2  Mary     121
3   Sam     122

In [61]:
df.drop(3)

NAME  Profit
0  John     100
1  Mark     110
2  Mary     121